Repository wecode-bootcamp-korea/fullstack2-1st-MRDR-backend, pull requests merged in 2021-10, with the labels that each got.

#6 Add: Prisma modeling, initial migration (함준범)
  package-lock.json
  package.json
  prisma/migrations/20211010044826_init_all_tables/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: Status:리뷰요청

#9 Fix: Prisma Modeling - products 테이블에 컬럼 추가
  prisma/migrations/20211010112106_add_column_detail_image_url_to_prdouct_model/migration.sql
  prisma/schema.prisma
Labels: Status:리뷰요청

#13 Fix:데이터관리로직 추가(박정훈)
  .DS_Store
  app.js
  controllers/procudtControllers.js
  dataUploader/amount.csv
  dataUploader/color.csv
  dataUploader/dataUploader.js
  dataUploader/mainCategory.csv
  dataUploader/product.csv
  dataUploader/productColorDetailImage.csv
  dataUploader/productColorImage.csv
  dataUploader/productImage.csv
  dataUploader/productSize.csv
  dataUploader/size.csv
  dataUploader/subCategory.csv
  dataUploader/typeCategory.csv
  models/productDetailDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/productRouter.js
  services/productServices.js
Labels: Status::Self Refactoring 완료

#16 Add: 인증/인가 기능 구현 (이성재)
  .gitignore
  app.js
  controllers/userController.js
  middlewares/index.js
  middlewares/validateToken.js
  models/index.js
  models/userDao.js
  routes/index.js
  routes/userRouter.js
  server.js
  services/userService.js
Labels: Status:리뷰요청

#17 Add: 상품 리스트 API 구현
  app.js
  controllers/index.js
  controllers/productController.js
  middlewares/paramValidation.js
  middlewares/validateToken.js
  models/index.js
  models/productDao.js
  routes/productRouter.js
  services/index.js
  services/productService.js
Labels: Status::Self Refactoring 완료, Status:리뷰요청

#23 Fix: Prisma Migrations 파일 복원
  prisma/migrations/20211010044826_init_all_tables/migration.sql
  prisma/migrations/20211010112106_add_column_detail_image_url_to_prdouct_model/migration.sql
  prisma/migrations/20211012071038_modfiy_model_about_color_image_cart/migration.sql
Labels: Status:리뷰요청

#30 Fix/signup connection(오작동 픽스)
  Upload/color.csv
  Upload/csvRead.js
  Upload/csvWriter.js
  Upload/imageTypes.csv
  Upload/mainCategory.csv
  Upload/product.csv
  Upload/productColorImage.csv
  Upload/productImage.csv
  Upload/productSize.csv
  Upload/size.csv
  Upload/subCategory.csv
  Upload/typeCategory.csv
  models/cartDao.js
  services/cartService.js
Labels: Status:Accepted

#31 Add: mysql dump 파일 추가
  mrdr-dump.sql
Labels: Status:리뷰요청
